AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a VPC for stelligent-u'
Metadata:
  SupportedResources: 'IAM'
Parameters:
  VpcName:
    Description: 'The name of the VPC being created.'
    Type: String
    Default: 'vpc-ajay'
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16
  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.192.20.0/24

Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: false
      EnableDnsHostnames: false
      Tags:
      - Key: Name
        Value: !Ref VpcName
      - Key: 'user'
        Value: 'ajay.anbuselvam.labs'
      - Key: 'stelligent-u-lesson'
        Value: '4.1'
      - Key: 'stelligent-u-lab'
        Value: '4.1.1'
      
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: 'user'
          Value: 'ajay.anbuselvam.labs'
        - Key: 'stelligent-u-lesson'
          Value: '4.1'
        - Key: 'stelligent-u-lab'
          Value: '4.1.1'
  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: 'user'
        Value: 'ajay.anbuselvam.labs'
      - Key: 'stelligent-u-lesson'
        Value: '4.1'
      - Key: 'stelligent-u-lab'
        Value: '4.1.1'
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref myInternetGateway
      VpcId: !Ref myVPC